shared:
  runs: 5
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
  log_dir: ./logs
dataset:
  name: Cora
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_feat_norm: False
  return_sparse: False
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.01
  wd: 0.01
model:
  model_name: signn
  sizes: [5, 2]
  hids: [128, 64]
  nchannels: 3
  T: 21 # Notice: T has to be divisible by 3
  v_threshold: 1.0
  alpha: 1.0
  p: 0.5
  dropout: 0.4
  aggr: mean
  sampler: sage
  neuron: BLIF
  surrogate: arctan
  concat: False
  enable_pre_lin: False
