shared:
  runs: 5
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
  log_dir: ./logs
dataset:
  name: Cora
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_feat_norm: False
  return_sparse: False
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.1
  wd: 0.01
  gnn_weight_decay: 0.0001
  trans_weight_decay: 0.001
model:
  model_name: spikegt
  hid_channels: 128
  num_heads: 2
  drop_rate: 0.7
  spike_mode: LIF
  T: 4
  trans_num_layers: 2
  graph_weight: 0.9
  aggregate: add
  gnn_num_layers: 2
  gnn_dropout: 0.1
  gnn_use_act: True
  gnn_use_bn: False
  gnn_use_residual: True
  gnn_use_init: False
  gnn_use_weight: False
