shared:
  runs: 5
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
  log_dir: ./logs
dataset:
  name: Cora
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_feat_norm: False
  return_sparse: False
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.0001
  wd: 0.01
  margin: 1.0
model:
  model_name: spikegcl
  hid_channels: 64
  T: 20
  v_threshold: 0.01
  alpha: 2.0
  dropout: 0.4
  dropedge: 0.4
  surrogate: sigmoid
  neuron: LIF
  reset: subtract
  act: elu
  bn: True
