shared:
  runs: 5
  epochs: 500
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
  device: cuda:2
  log_dir: ./logs
dataset:
  name: Cora
  task: lp
  root: ./data
  metric_type: acc
  criterion: cross_entropy
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.001
  wd: 0.01
  margin: 0.1
model:
  model_name: spikegcl
  hid_channels: 128
  T: 20
  v_threshold: 0.00001
  alpha: 2.0
  dropout: 0.6
  dropedge: 0.2
  surrogate: sigmoid
  neuron: LIF
  reset: subtract
  act: elu
  bn: True