shared:
  runs: 5
  epochs: 300
  eval_step: 20
  patience: 10
  seed: 123
  gpu: 0
  device: cuda:2
  log_dir: ./logs
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
dataset:
  name: Pubmed
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_sparse: False
opt:
  lr: 0.01
  wd: 0.0
model:
  model_name: mpnn
  conv_type: gat
  hid_channels: 128
  dropout: 0.0
  num_layers: 1
  heads: 2
  norm_type: ln
  enable_res: True
  enable_jk: False
  enable_pre_lin: False