shared:
  runs: 5
  epochs: 300
  eval_step: 20
  patience: 10
  seed: 123
  gpu: 0
  log_dir: ./logs
dataset:
  name: Pubmed
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_sparse: False
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 99999999
opt:
  lr: 0.1
  wd: 0.0001
model:
  model_name: signn
  sizes: [5, 2]
  hids: [64, 32]
  nchannels: 3
  T: 12 # Notice: T has to be divisible by 3
  v_threshold: 1.0
  alpha: 1.0
  p: 0.5
  dropout: 0.0
  aggr: mean
  sampler: sage
  neuron: BLIF
  surrogate: arctan
  concat: False
  enable_pre_lin: False
