shared:
  runs: 5
  epochs: 300
  eval_step: 20
  patience: 10
  seed: 123
  gpu: 0
  log_dir: ./logs
dataset:
  name: Cora
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_sparse: False
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 99999999
opt:
  lr: 0.001
  wd: 0.1
model:
  model_name: spikenet
  sizes: [5, 2]
  hids: [128, 64]
  aggr: mean
  sampler: sage
  neuron: LIF
  T: 10
  surrogate: arctan
  alpha: 1.0
  dropout: 0.0
  concat: False
  enable_pre_lin: False
