shared:
  runs: 1
  epochs: 200
  eval_step: 20
  patience: 30
  seed: 123
  gpu: 0
dataset:
  name: Cora
  root: none
  metric_type: accuracy
  criterion: cross_entropy
loder:
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.001
  wd: 0.0
model:
  model_name: drsgnn
  T: 200
  nb_pos_enc: 8