shared:
  runs: 1
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
dataset:
  name: Cora
  root: none
  metric_type: accuracy
  criterion: cross_entropy
loder:
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.01
  wd: 0.001
model_name: msg
model:
  T: 20
  num_layers: 2
  step_size: 0.01
  manifold: [sphere]
  embed_dim: [32]
  v_threshold: 1.0
  dropout: 0.1
  neuron: LIF
  delta: 0.05
  tau: 2.0
  use_product: false
  use_MS: true