shared:
  runs: 1
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
dataset:
  name: Cora
  root: none
  metric_type: accuracy
  criterion: cross_entropy
loader:
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.001
  wd: 0.0
model:
  model_name: signn
  sizes: [5, 2]
  hids: [128, 32]
  nchannels: 3
  T: 21 # Notice: T has to be divisible by 3
  v_threshold: 1.0
  alpha: 1.0
  p: 0.5
  dropout: 0.6
  aggr: mean
  sampler: sage
  neuron: BLIF
  surrogate: arctan
  concat: False