shared:
  runs: 1
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
dataset:
  name: Cora
  root: none
  metric_type: accuracy
  criterion: cross_entropy
loader:
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.001
  wd: 0.0
model:
  model_name: spikenet
  sizes: [5, 2]
  hids: [128, 64]
  aggr: mean
  sampler: sage
  neuron: LIF
  T: 20
  surrogate: arctan
  alpha: 1.0
  dropout: 0.6
  concat: False