shared:
  runs: 1
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
dataset:
  name: Cora
  root: none
  metric_type: accuracy
  criterion: cross_entropy
loder:
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.001
  wd: 0.0001
  margin: 1.0
model_name: spikegcl
model:
  hid_channels: 64
  T: 20
  v_threshold: 0.01
  alpha: 2.0
  dropout: 0.0
  dropedge: 0.2
  surrogate: sigmoid
  neuron: LIF
  reset: subtract
  act: elu
  bn: True