shared:
  runs: 1
  epochs: 200
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
dataset:
  name: Cora
  root: none
  metric_type: accuracy
  criterion: cross_entropy
loader:
  loader_type: neighbor
  batch_size: 2048
opt:
  lr: 0.001
  wd: 0.0
model_name: stfn
model:
  hid_channels: 128
  T: 20
  v_threshold: 1.0
  backbone: gcn
  num_heads: 4