shared:
  runs: 5
  epochs: 300
  eval_step: 20
  patience: 5
  seed: 123
  gpu: 0
  device: cuda:0
  log_dir: ./logs
dataset:
  name: ogbl-collab
  task: lp
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_sparse: False
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
opt:
  lr: 0.0001
  wd: 0.0001
model:
  model_name: msg
  T: 5
  num_layers: 2
  step_size: 0.1
  manifold: [euclidean]
  embed_dim: [128]     
  v_threshold: 3.0
  dropout: 0.5
  neuron: LIF
  delta: 0.05
  tau: 2.0
  use_product: False
  use_MS: True
  hid_channels: 64