shared:
  runs: 5
  epochs: 500
  eval_step: 20
  patience: 10
  seed: 123
  gpu: 0
  log_dir: /home/hzzhang/SGNNBenchmark/logs/gasnn
  device: cuda:2
dataset:
  name: Pubmed
  task: lp
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_feat_norm: False
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
  num_neighbors: 2
opt:
  lr: 0.001
  wd: 0.001
model:
  model_name: stfn
  hid_channels: 256
  neuron: LIF
  T: 20
  v_threshold: 1.0
  backbone: gat
  num_heads: 4
  num_layers: 1
  norm: stfn
  enable_res: False
  enable_jk: False