shared:
  runs: 5
  epochs: 300
  eval_step: 20
  patience: 10
  seed: 123
  gpu: 0
  device: cuda:2
  log_dir: ./logs
loader:
  enable_loader: False
  loader_type: neighbor
  batch_size: 1024
dataset:
  name: Cora
  root: ./data
  metric_type: acc
  criterion: cross_entropy
  enable_sparse: False
opt:
  lr: 0.001
  wd: 0.0001
model:
  model_name: mpnn
  conv_type: sage
  hid_channels: 256
  num_layers: 2
  dropout: 0.0
  norm_type: bn
  enable_res: True
  enable_jk: True
  enable_pre_lin: False